import type { WeaponDefinition, WeaponId, WeaponSlot } from './types';

export const WEAPON_DEFINITIONS: Readonly<Record<WeaponId, WeaponDefinition>> = Object.freeze({
  rifle: Object.freeze({
    id: 'rifle',
    slot: 1,
    label: '自动步枪',
    hint: '自动连射 · 开镜精准射击',
    fireMode: 'automatic',
    fireInterval: 0.095,
    damage: 24,
    spread: 0.009,
    magazineSize: 30,
    initialReserve: 150,
    reloadDuration: 1.55,
    recoil: 0.68,
    range: 120,
    adsFov: 48,
    knockback: 2.8,
    switchDuration: 0.36,
  }),
  shotgun: Object.freeze({
    id: 'shotgun',
    slot: 2,
    label: '霰弹枪',
    hint: '近距散射 · 一枪击退',
    fireMode: 'semi',
    fireInterval: 0.78,
    damage: 15,
    spread: 0.072,
    magazineSize: 6,
    initialReserve: 30,
    reloadDuration: 1.9,
    recoil: 1.75,
    range: 34,
    adsFov: 58,
    knockback: 14,
    pellets: 9,
    actionDuration: 0.58,
    switchDuration: 0.4,
  }),
  revolver: Object.freeze({
    id: 'revolver',
    slot: 3,
    label: '左轮手枪',
    hint: '六发重击 · 稳住准星',
    fireMode: 'semi',
    fireInterval: 0.44,
    damage: 68,
    spread: 0.0045,
    magazineSize: 6,
    initialReserve: 36,
    reloadDuration: 1.82,
    recoil: 1.42,
    range: 95,
    adsFov: 44,
    knockback: 7,
    switchDuration: 0.3,
  }),
  sniper: Object.freeze({
    id: 'sniper',
    slot: 4,
    label: '狙击步枪',
    hint: '远距狙击 · 一枪抹除',
    fireMode: 'semi',
    fireInterval: 1.08,
    damage: 150,
    spread: 0.00075,
    magazineSize: 5,
    initialReserve: 25,
    reloadDuration: 2.25,
    recoil: 2.05,
    range: 240,
    adsFov: 24,
    knockback: 12,
    actionDuration: 0.82,
    switchDuration: 0.46,
  }),
  katana: Object.freeze({
    id: 'katana',
    slot: 5,
    label: '武士刀',
    hint: '挥刀斩击 · 按住瞄准格挡反弹',
    fireMode: 'melee',
    fireInterval: 0.42,
    damage: 110,
    spread: 0,
    magazineSize: null,
    initialReserve: null,
    reloadDuration: 0,
    recoil: 0.4,
    range: 4.4,
    adsFov: 68,
    knockback: 9,
    actionDuration: 0.42,
    switchDuration: 0.28,
  }),
});

export const SLOT_TO_WEAPON: Readonly<Record<WeaponSlot, WeaponId>> = Object.freeze({
  1: 'rifle',
  2: 'shotgun',
  3: 'revolver',
  4: 'sniper',
  5: 'katana',
});

export function weaponIdForSlot(slot: number): WeaponId | null {
  if (!Number.isInteger(slot) || slot < 1 || slot > 5) return null;
  return SLOT_TO_WEAPON[slot as WeaponSlot];
}
